apiVersion: v1
kind: Pod
metadata:
  name: app-test
  namespace: application
spec:
  containers:
#  - image: acrdevakshislmgtuksouth001abfimd.azurecr.io/testimages/nginx:latest
  - image: memcached
    name: app-test
    resources:
      requests:
        memory: "64Mi"
        cpu: "19m"
      limits:
        memory: "128Mi"
        cpu: "500m"
