apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: bc-prod
spec:
  containers:
  - image: httpd
    name: web1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
