apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application
    istio.io/rev: asm-1-17
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: application-quota
  namespace: application
spec:
  hard:
#    requests.cpu: 1000m
#    requests.memory: 2Gi
    limits.cpu: 2000m
    limits.memory: 4Gi
